; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = ATtiny414

[env]
platform = atmelmegaavr
framework = arduino
upload_speed = 115200
upload_flags = 
	--tool
	uart
	--device
	$BOARD
	--uart
	$UPLOAD_PORT
	--clk
	$UPLOAD_SPEED
upload_command = venv/bin/pymcuprog write --erase --verify $UPLOAD_FLAGS --filename $SOURCE
upload_port = /dev/ttyUSB1
board_build.f_cpu = 20000000L
build_flags = 
 	-DDEMO
 	; -DATTINY_RING
	; -DATTINY_RING_412

[env:ATtiny414]
board = ATtiny414

[env:HANGING_PLASTIC_STAR]
board = ATtiny414
build_flags = -DHANGING_PLASTIC_STAR

[env:TAHU_DIORAMA]
board = ATtiny414
build_flags = 
	-DTAHU_DIORAMA
	-DUSE_EEPROM=1

[env:HALLOWEEN_STAKE_LIGHTS]
board = ATtiny414
build_flags = 
	-DHALLOWEEN_STAKE_LIGHTS
	-D COLOUR_ORDER=NEO_GRBW
	; -DUSE_EEPROM=1

[env:SPAIN_LIGHTHOUSE]
board = ATtiny414
build_flags = 
	-DSPAIN_LIGHTHOUSE
	-DATTINY_STAR
	-D COLOUR_ORDER=NEO_GRBW

[env:CROWN_CORK]
; board = ATtiny414
board = ATtiny814
build_flags = 
 	-DCROWN_CORK
 	-DUSE_EEPROM=1

[env:PILL_POT]
; board = ATtiny414
board = ATtiny814
build_flags = 
 	-DPILL_POT
 	-DUSE_EEPROM=1

[env:DAD_CROWN_CORK]
board = ATtiny414
build_flags = 
 	-DDAD_CROWN_CORK
	-D COLOUR_ORDER=NEO_GRBW
	; -D COLOUR_ORDER=NEO_RGBW

[env:ATtiny412]
board = ATtiny412

[env:ATtiny412_Ring_Demo]
board = ATtiny412
build_flags = 
 	-DDEMO
	-DATTINY_RING_412

[env:ATtiny414_Star_Demo]
board = ATtiny414
build_flags = 
 	-DDEMO
	-DATTINY_STAR

[env:ATtiny814]
board = ATtiny814
build_flags = 
 	-DDEMO_814

[env:Snowglobe]
# Snowglobe led ring
board = ATtiny414
build_flags = 
 	-DSNOWGLOBE
	-DATTINY_RING

[env:Halloween_Snake_Jar]
# Halloween Snake in "formaldehyde" jar prop
board = ATtiny414
build_flags = -DHALLOWEEN_SNAKE_JAR

[env:Xmas_Tree]
# 3D printed Christmas Tree with 5mm Through Hole WS2812
board = ATtiny414
build_flags = 
	-DXMAS_TREE
	-D COLOUR_ORDER=NEO_RGB

[env:Ada_Xmas_Tree]
# 3D printed Adafruit Christmas Tree with ring PCB
board = ATtiny414
build_flags = 
	-DATTINY_RING
	-DADA_XMAS_TREE

[env:Cooling_Tower]
# 3D printed cooling tower with ring PCB
board = ATtiny414
build_flags = 
	-DATTINY_RING
	-DCOOLING_TOWER

[env:Pattern_Lamp]
# Repourposed lamp from The Range with ring PCB
board = ATtiny414
build_flags = 
	-DATTINY_RING
	-DPATTERN_LAMP

[env:Christmas_House]
# 3D printed Christmas "snowglobe" with house and 5mm Through Hole WS2812
board = ATtiny414
build_flags = 
	-DCHRISTMAS_HOUSE
	-D COLOUR_ORDER=NEO_RGB

[env:Blue_Crystal_Formation]
# 3D printed crystal formation
board = ATtiny414
build_flags = -DBLUE_CRYSTAL_FORMATION

[env:Glass_Bottle]
# Hobbycraft Glass Bottle
board = ATtiny414
build_flags = -DGLASS_BOTTLE

[env:Easter_Egg_Lamp]
# 3D Printed Easter egg lamp with 7-led "star"/"jewel" PCB
board = ATtiny414
build_flags = 
 	-DEASTER_EGG_LAMP
	-DATTINY_STAR

[env:HouseSnowglobe]
# 3D Printed Easter egg lamp with 7-led "star"/"jewel" PCB
board = ATtiny414
build_flags = 
	-DCHRISTMAS_HOUSE
	-DATTINY_STAR

[env:Crysyal_Formation]
# 3D Printed crystal formation with 7-led "star"/"jewel" PCB
board = ATtiny414
build_flags = 
 	-DCRYSTAL_FORMATION
	-DATTINY_STAR


; run the following command to set fuses
; pio run -t fuses -e set_fuses
[env:set_fuses]
board = ATtiny814
upload_flags =
; Hardware settings
; board_hardware.bod = 2.7v
board_hardware.eesave = yes
board_hardware.updipin = updi
